### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dpkoch**
I've heavily refactored the code in this package, to the point that it's probably unrecognizable. My main rationale were the following:
- The method I was using to abstract away the mavlink details was confusing and way too clumsy; adding support for new messages was pain. I designed it with good intentions, but ended up hating it.
- The way parameters were handled was awkward
- Individual classes were doing way too much, making the code hard to read and maintain

**Organization:**
As before, the code is still split into two main parts:
1. The `mavrosflight` library, which handles the low-level interfacing to the serial link but none of the ROS stuff
2. The `fcu_io` executable that handles all of the ROS I/O

The main difference with the new code is that I've reduced the level of abstraction so that the `fcu_io` side now deals directly with mavlink data types. This means that anyone wanting to interface with the `mavrosflight` library now has to understand a little bit about mavlink, but I think that the reduced complexity and better clarity are well worth that tradeoff.

**Summary of changes:**
- Split the mavrosflight library into several sub-components: a serial handler, parameter manager, and top-level interface class.
- Implemented a parameter manager that keeps a local copy of the parameters to enable actually accessing and using the values. It also abstracts away the underlying mavlink protocol and provides a simple interface for getting, setting, and saving parameter values.
- Implemented a listener interface for new messages and parameter events. Classes inherit from the interface class definitions by overriding callback functions, then register themselves as listeners to receive new messages and parameter events.
- Ditched the overly-complicated boost function abstraction design. `fcu_io` now directly receives and sends mavlink message types

**Notes**
One downside of this change is that now more of the low-level details are not taken care of in the mavrosflight library (like the diff pressure handler in `fcu_io`, which is pretty gross). That means that anyone else who wants to build off of this library in the future will have to duplicate those pieces of the code. So in the future we'll probably want to figure out how to abstract those things a little more, but the way I was doing just wasn't working, so I think this is better for now.

### CODE REVIEW

**Comment by superjax** [comment]
Wow!  You've done a _ton_ of work!  Nicely done!

I love this new version.  I am still not 100% sure how the parameter manager works, but I really like the removal of the layers between fcu_io and the actual handling of messages (that was a little convoluted before).

I have two questions,  mainly about the parameters
1. Do you think it makes sense to copy the parameters to the rosparam server?  Or would that just get complicated?  I guess most of these parameters really have very little to do with the ROS side of things anyway, but since things like gains are technically params, it might be nice to be able to specify them in a launch file.  My concern is that if we were to do that, the we would be keeping information synced between 3 servers, rather than 2.  What do you think?
2. If we were to hook up the ROS parameter server, should we then also hook up rqt_reconfigure?  I guess that goes back to my question in #4.

I don't think that these have anything to do with the pull request though.  Your code looks great, and I don't have any beef with it at all, but let me test it out real quick, and I'll merge it if it all works on my end.

**Comment by superjax** [comment]
Also, sorry about the `diff_pressure`.  It is a little gross, unfortunately, the barometer stuff I just wrote is similar.  I don't know a better way to do it, especially the calibration stuff.  If we could get away with just scaling or some multiplication or something that would be better, but the calibration is pretty important.

Maybe we could make a generic sensor class which has internal calibration and scaling functions, where we inherit a version for each sensor?

Just an idea.

**Comment by superjax** [comment]
I love the new param services.... These are fantastic.  I love how it tells you there are unsaved parameters, you don't have to type '6' anymore, because it automagically figures out what the type is... I am totally impressed.

I have one enhancement I think we should add, but that's all (as an issue, not necessarily before merging)
1. We should only publish topics when we receive the first message from mavlink.  For example, there is no reason to publish /diff_pressure if there are no mavlink messages being passes.  Later on, we will have barometer and magnetometer as well, which could clutter up the node.

**Comment by dpkoch** [comment]
Yeah I've thought about trying to use the rosparam server. I think it would add a couple of extra things to figure out, but it would also be nice to keep everything more ROS-oriented. I plan on playing with that to see if it makes sense. If we go that route dynamic reconfigure would be pretty cool, although it would also make maintenance harder since we'd have to keep the dynamic reconfigure config file up to date with the onboard parameters. Something to look into though.

Making a sensor class could be a good idea. It'd be a little complicated since each sensor returns a different number of values, but maybe we could at least have some functions available in mavrosflight to do the calibration or something. I think figuring something out along those lines is worth doing.

Glad you like the param services! Just FYI, I decided to do everything with params on the ROS side as doubles. That way you can store floating point values, but a double can also exactly store (as an int in the mantissa) any integer value that an int32 or uint32 can, so we won't have any problems with floating point precision messing up our integer values. Then the actual parameter types are handled internally and invisible to the user.

I agree with not publishing the topic until we receive the first message; I'll create an issue for that.

**Pull request merged**
