### PR TITLE
Sensor abstraction and time synchronization

### LINKED ISSUE #20: Sensor calibration abstraction
It'd be nice for things like accelerometer scaling and barometer / differential pressure calculations to be abstracted away and hidden from the user. We could do something like have an abstract sensor class that is inherited for each sensor, or just functions available that apply the calibration to incoming mavlink messages.

### PR DESCRIPTION
**Pull request by dpkoch**
This pull request accomplishes the following:
- Abstracts sensor calibration methods (closes #20)
- Time synchronization

This is linked to BYU-MAGICC/ROSflight2#34

### CODE REVIEW

**Comment by superjax** [comment]
Looks awesome!  Thanks.

I have some questions, mainly about the mavlink library.  Can we put an `int16_t` field for temperature on the IMU message, and make the stamp a `uint32_t`, rather than a signed `int32_t`? I guess this is part of BYU-MAGICC/mavlink#3.

I was also going to put my temperature calibration code in the `imu::correct` function

**Comment by dpkoch** [comment]
Alright don't merge just yet, I've still got to update the mavlink reference.

I guess we'll have to publish IMU temperature on a separate ROS topic. Do you happen to know what the conversion is from raw bits to degC?

**Comment by dpkoch** [comment]
Oh just kidding, I just saw your last comment. Sounds great, I'll get the mavlink updated real quick.

**Comment by superjax** [comment]
Okay.  It's `double temperature = ((float)imu.temp/340.0 + 36.53)`

**Comment by dpkoch** [comment]
Okay I'll put it in, thanks

**Comment by superjax** [comment]
hahaha, sorry, I just happened to be really on top of it there.  Just let me know when you're ready for me to merge these in.

**Comment by dpkoch** [comment]
Go for it.

**Pull request merged**
